### ISSUE TITLE
Milestone 03 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/picfixR#17]
Hi,

Thanks for your efforts in milestone 03 submission. I've just reviewed your submission and I have few comments/suggestions below.

- [x] Your package installation runs without any problems 
- [x] You have provided very comprehensive test cases that I cannot think of any more 
- [x] You have provided a vignette for the R package 
- [x] You have provided an open source license 
- [x] You have provided good documentation of your function
- [x] You provided your branch coverage results
- I suggest you use `import colorscience` or `importFrom colorscience RBG2HSL` to make it easier for users not having to import the library themselves.
- I got an error running your `sharpen()` function, maybe because you wrote the function `RBG2HSL()` in lowercase letters, please check.

Thanks!

**Comment by GeorgeJJW** [comment]
Thanks for the timely feedback.

As discussed in person, we broke the `vibrance` function in a commit (#16), but the release intended for submission for milestone 3 from last week, [v2.0](https://github.com/UBC-MDS/picfixR/tree/v2.0), should be working flawlessly.

For your reference, the milestone 3 version can be installed via the R console command `devtools::install_github("UBC-MDS/picfixR@v2.0")`.

Thank you once again for your throughout feedback and taking the time to actually see if each of our functions work!
